README.md

Right now it links to https://github.com/akira/exq/blob/master/redis.io

Update README - fix Redis website url

---

mix.exs

and grab it from hex instead of github.
(Exq is not affected by any of the breaking changes: https://github.com/zyro/elixir-uuid/blob/master/CHANGELOG.md#v100-09-mar-2015-elixir--10.)

Update uuid dependency to 1.0.0

---

web/router.ex

Response should be sent to conn in a chain to return proper connection and avoid Plug.Conn.NotSentError
Steps to reproduce the error:
1. Open http://localhost:4040 in a browser to get /api/realtimes requests
2.
```
$ iex -S mix
iex(1)> {:ok, _} = Plug.Adapters.Cowboy.http Exq.RouterPlug, [namespace: ""], port: 4040 
23:44:06.518 [error] #PID<0.310.0> running Exq.RouterPlug terminated
Server: localhost:4040 (http)
Request: GET /api/realtimes
** (exit) an exception was raised:
** (Plug.Conn.NotSentError) no response was set nor sent from the connection
(plug) lib/plug/adapters/cowboy/handler.ex:42: Plug.Adapters.Cowboy.Handler.maybe_send/2
(plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
(cowboy) src/cowboy_protocol.erl:435: :cowboy_protocol.execute/4 …
```

Response should be sent to conn in a chain

---

README.md
lib/exq/manager.ex
lib/exq/redis_queue.ex
lib/exq/stats.ex
lib/exq/worker.ex
test/exq_test.exs
test/redis_queue_test.exs
test/worker_test.exs

Keep a count on the manager level and throttle if going over this count.
This is a simple solution for now - could be changed once we go to Queue level
concurrency / worker supervision

Allow throttling for number of concurrent workers

---

lib/exq/job.ex
lib/exq/redis_queue.ex
lib/exq/stats.ex

I was running into an issue that was causing exq to crash when `Exq.Stats.remove_process` was called. The reason for the crash was due to JSON parsing errors when reading from the `processes` set in Redis.
While vanilla Sidekiq only places valid JSON into `processes`, there are a few common Ruby Sidekiq plugins which insert other things. In my case, the [sidekiq-limit_fetch](https://github.com/brainopia/sidekiq-limit_fetch) plugin was inserting string hashes into the `processes` set.
So I've wrapped Poison's non-bang `encode()` and `decode()` functions in `Exq.Json`, and renamed the previous `encode()` and `decode()` functions there to match the underlying Poison function (ie. `encode!()` and `decode!()`)
If this change breaks things for people *(perhaps they were relying on the existing …

Handle JSON parsing errors in Exq.Stats.remove_process

---

lib/exq/redis.ex

Since it's the same as [`lib/exq/redis.ex#L44-L47`](https://github.com/akira/exq/blob/master/lib/exq/redis.ex#L44-L47)

remove duplicate `llen!` method

---

README.md
lib/exq.ex
lib/exq/api.ex
lib/exq/enqueuer.ex
lib/exq/manager.ex
lib/exq/redis.ex
lib/exq/redis_queue.ex
lib/exq/scheduler.ex
lib/exq/scheduler_sup.ex
lib/exq/stats.ex
mix.exs
mix.lock
test/exq_test.exs
test/performance_test.exs
test/redis_queue_test.exs
test/redis_test.exs
web/router.ex

Based off #8 I have added a Task Scheduler, 
It uses "scheduled" queues for each "live" queue which are sorted sets, when a scheduled job's time is reached the job is pulled from the "scheduled" queue and put on the "live" queue and then the manager deals with it as normal.
I'm new to Elixir so I thought it best to get some feedback before I went any further.
It is working and api wise I think enqueue_in works but I'm not sure about the format for the time in enqueue_at, currently its a unix timestamp.
At the moment the jobs are scheduled with a 1 second resolution which works for me but I'm not sure how accurate others need the scheduling to be.
I thought my next steps should be to add a setting to enable the scheduler which would default to false and also add tests and documentation for …

Add scheduled jobs

---

lib/exq/worker/server.ex
test/worker_test.exs

Hi,
I am currently running a web app written in Ruby using Sidekiq
and am trying to migrate my workers to Elixir using exq, while keeping my Ruby app and using
only Sidekiq client to push the jobs.
My workers in Ruby are in nested modules (e.g. `MyApp::MyWorker`), which makes the jobs impossible to process
with exq without (AFAIK) either changing my Ruby app layout, or stopping to use Sidekiq to queue the jobs,
as the produced JSON is something like this:
```
{
"retry":true,
"queue":"default",
"class":"MyApp::MyWorker",
"args":["myarg"],
"jid":"ded64b6bd566ee8c204eb685",
"enqueued_at":1442650846.397662
}
```
As exq is compatible with Sidekiq and Resque, I think that allowing nested modules could
make the migration easier for cases like mine, using an existing Ruby code base.
This would …

Add support for nested Ruby modules.

---

lib/exq/redis/job_queue.ex

In certain cases, :none is returned for job, handle situation in dequeue_random.

Dequeue multiple queues fix

---

lib/exq/enqueuer/server.ex
lib/exq/manager/server.ex
lib/exq/redis/connection.ex
lib/exq/redis/job_queue.ex
lib/exq/stats/server.ex
lib/exq/stats/supervisor.ex
test/failure_scenarios_test.exs
test/flaky_connection_test.exs
test/job_queue_test.exs
test/redis_test.exs

* Catch and handle exceptions related to Redis
* Take out this handling from JobQueue and bubble results up
* Manager back off in case of any Redis errors
* Enqueue to return errors in case of Redis issues
To be done:
* Long term plan is to break out each queue fetcher to a separate
GenServer so we can use BRPOPLPUSH, so this logic would be moved there.

Better handling if Redis is down - bubble up errors

---

lib/exq/manager/server.ex
lib/exq/redis/job_queue.ex
lib/exq/redis/job_stat.ex
lib/exq/stats/server.ex
lib/exq/worker/server.ex

If you wish 😉
There are still two warnings when running `mix`:
```
lib/exq/redis/job_queue.ex:229: warning: function dequeue_random/3 is unused
```
should it be removed?
```
lib/exq/support/process.ex:1: warning: redefining module Exq.Support.Process
```
Looks like `Exq.Stats.Process` should exist:
```
$ ag Exq.Support.Process
lib/exq/stats/process.ex
1:defmodule Exq.Support.Process do
lib/exq/support/process.ex
1:defmodule Exq.Support.Process do
```

Removed some Elixir compilation warnings

---

mix.exs

When running a compiled erlang release, rather than using mix, uuid won't be available unless it's in the mix applications list.

Add uuid to mix applications

---

lib/exq/support/opts.ex
test/config_test.exs
test/test_helper.exs

The URL takes precedence over the host, password, port and database connection options.

Allow the Redis connection to be setup via a URL

---

lib/exq/redis/job_queue.ex
lib/exq/redis/job_stat.ex
lib/exq/support/job.ex

Used [Credo](https://github.com/rrrene/credo) to do this.
I've found that the code is fairly clean already. :+1: 
One interesting part is in `lib/exq/support/job.ex`, `to_json` creates a HashDict but doesn't use it for converting to JSON.
(sidenote: my first elixir-based PR! :tada:)

Run through linter and cleanup a few cases

---

lib/exq/enqueue_api.ex
lib/exq/enqueuer/server.ex
lib/exq/enqueuer/supervisor.ex
lib/exq/manager/server.ex
lib/exq/middleware/server.ex
lib/exq/redis/connection.ex
lib/exq/redis/job_queue.ex
lib/exq/scheduler/server.ex
lib/exq/stats/server.ex
lib/exq/support/config.ex
lib/exq/support/opts.ex
lib/exq/worker/supervisor.ex

This will close #163 
Copied configuration from `config.exs` to `lib/exq/support/config.ex` and made `Config.get/1` to fetch the corresponding value if fallback isn't given.

Centralize configuration

---

lib/exq/middleware/logger.ex
lib/exq/redis/job_queue.ex
lib/exq/redis/job_stat.ex
lib/exq/stats/server.ex
mix.exs
mix.lock
test/job_queue_test.exs
test/job_stat_test.exs

- Timex 2.0 doesn't support `Date.universal` and is replaced with `DateTime.universal`
- DateTime formatter was moved and the DateFormat module no longer exists
- Cleans up a bunch of warnings about secs/seconds, usecs/microseconds
fixes #179

Updates for Timex 2.0.0

---

mix.exs
mix.lock
test/job_queue_test.exs

Hi,
I was trying to upgrade my app to Poison 2 and ran into a dependency issue.
The API used in `Exq.Support.Json` should work with both 1.x and 2.x, so I think
it is ok to relax the dependency.
I also updated the lock file to use 2.x in the tests, but let me know if you would rather
stick with 1.x there.
Thanks!

Allow poison 2.

---

lib/exq/enqueue_api.ex

Change time unit from milliseconds to seconds.
As we can see in `exq/lib/exq/redis/job_queue.ex:59`, the provided
offset is multiplied by `1_000_000` at treated as a value in
`microseconds`.
(I actually found out that by waiting 10 minutes for a job to process in
production :[ )

Fix `EnqueuerApi#enqueue_at` offset time units doc

---

lib/exq/api/server.ex
lib/exq/enqueuer/server.ex
lib/exq/middleware/server.ex
lib/exq/scheduler/server.ex
lib/exq/stats/server.ex
lib/exq/support/mode.ex
lib/exq/support/opts.ex
lib/exq/worker/supervisor.ex

Hi, this fixes the imperative assignment warnings introduces in Elixir 1.3
http://elixir-lang.org/blog/2016/06/21/elixir-v1-3-0-released/
There are absolutely no changes in the functionality.

Fix unsafe variable warnings

---

lib/exq/middleware/job.ex
lib/exq/middleware/pipeline.ex
lib/exq/redis/connection.ex
lib/exq/worker/server.ex
test/middleware_test.exs
test/redis_test.exs

- Add a new flag `terminated` in `Exq.Middleware.Pipeline` to halt the execution of the pipeline AND the worker
- Add `zcount!` and `sismember!` in `Exq.Redis.Connection` as utility function
- Add logic to handle `terminated` flag in pipeline in `Exq.Worker.Server`
- Expose `Exq.Middleware.Job.remove_job_from_backup/1` as public function instead of private
- Add tests for `terminated` flag as well as `zcount!` and `sismember!` in `Exq.Redis.Connection` module
Note: @akira I add a bit logic into Exq.Worker.Server to handle the termination of a job. The expected behaviour of this flag, when set to true, is to halt the execution of the pipeline AND prevent the job from getting dispatched. I haven't figured out a better way of getting the same behaviour. So, if you got any idea or concern …

Throttler integration

---

lib/exq/support/mode.ex

```
18:17:35.698 [error] GenServer Exq terminating
** (stop) exited in: GenServer.call(Exq.Worker.Sup, {:start_child, ["{\"retry\":5,\"queue\":\"email_notification\",\"backtrace\":true,\"class\":\"EmailService\",\"args\":[\"47e861f3-b531-4c3e-885d-209638be7736\",{\"order_id\":\"o2323\",\"merchant_id\":\"A0123123\",\"subject\":\"[testing] Notifikasi email valid 1\",\"from\":{\"name\":\"PATO\",\"email\":\"pato@veritrans.co.id\"},\"to\":[{\"name\":\"andri\",\"email\":\"ananthakumaran@gmail.com\"},{\"name\":\"ak\",\"email\":\"ananthakumaran+3@gmail.com\"}],\"cc\":[{\"name\":\"andri\",\"email\":\"ananthakumaran@gmail.com\"},{\"name\":\"ak\",\"email\":\"ananthakumaran+3@gmail.com\"}],\"bcc\":null,\"text_body\":\"Ini adalah isi email dengan format text.\",\"html_body\":\"<!DOCTYPE html PUBLIC …
```

Fix possible race condition on startup

---

README.md

Brings more visibility into outdated dependencies on `README.md`:
[![Deps Status](https://beta.hexfaktor.org/badge/all/github/akira/exq.svg?branch=master)](https://beta.hexfaktor.org/github/akira/exq) 🍺
https://beta.hexfaktor.org/github/akira/exq
It looks like repo's owner gotta sign up, so the service does monitor for deps updates.

Add hexfactor badge

---

lib/exq/worker/server.ex
test/middleware_test.exs

This will provide interaction between worker and middleware. 
Usecase: Retry the job 5 times in normal circumstances, but also allow the worker to kill the job right away if some essential conditions are not met. This could be done easily by a middleware, if the worker return value is available in the pipeline.

add job result and raw exception in pipeline

---

lib/exq/node_identifier/behaviour.ex
lib/exq/node_identifier/hostname_identifier.ex
lib/exq/redis/job_queue.ex
lib/exq/support/config.ex
test/api_test.exs

This is used for backup and restore purposes when a node crashes. This provides
a behaviour that can be plugged in instead of using hostname.
Fixes #217

Provide ability to customize node ID

---

lib/exq/api.ex
lib/exq/api/server.ex
lib/exq/redis/job_queue.ex
test/api_test.exs

To support https://github.com/akira/exq_ui/issues/5 I couldn't find any way in the current exposed API to retry a job immediately, so I had a go at adding the ability to immediately enqueue a retry, removing it from the retry queue.
I'm still pretty new to elixir so happy for feedback and to make adjustments.

Expose retry via Exq.Api

---

lib/exq/manager/server.ex
lib/exq/node_identifier/behaviour.ex
lib/exq/node_identifier/hostname_identifier.ex
lib/exq/redis/job_queue.ex

Refactor node identifier to manager, rename host to node_id
Helps with #217

Configurable node identifier. Use node_id instead of host

---

README.md
lib/exq/enqueue_api.ex
lib/exq/enqueuer/server.ex
lib/exq/manager/server.ex
lib/exq/redis/job_queue.ex
test/exq_test.exs
test/job_queue_test.exs
test/performance_test.exs

**Usage**
```ex
{:ok, ack} = Exq.enqueue(Exq, "default", "MyWorker", ["arg1", "arg2"])
{:ok, ack} = Exq.enqueue(Exq, "default", "MyWorker", ["arg1", "arg2"], max_retries: 10)
{:ok, ack} = Exq.enqueue(Exq, "default", "MyWorker", ["arg1", "arg2"], max_retries: 0)
```
Limit `Exq.Support.Job.retry` only be `Integer`(no boolean).
https://github.com/akira/exq/issues/215
#224

add max_retries options for per worker

---

config/test.exs
lib/exq/redis/connection.ex
lib/exq/redis/job_stat.ex
lib/exq/stats/server.ex
lib/exq/support/config.ex
test/worker_test.exs

Stats updates are currently being sent to Redis one at a time. This causes a situation
where stats updates can fall behind other parts of the system and cause memory to be eaten up.
This commit changes stats to flush batches of updates at a time. This allows the stats to
keep up with other parts of the system and update Redis more efficiently.
#122 #231

Flush stats on interval using Redis batch API

---

lib/exq.ex
lib/exq/api/server.ex
lib/exq/manager/server.ex
lib/exq/redis/job_queue.ex
lib/exq/scheduler/server.ex
lib/exq/serializers/json_serializer.ex
lib/exq/support/time.ex
lib/exq/worker/server.ex
mix.exs
test/api_test.exs
test/exq_test.exs
test/failure_scenarios_test.exs
test/flaky_connection_test.exs
test/middleware_test.exs
test/performance_test.exs
test/test_helper.exs
test/worker_test.exs

* Parentheses for method calls
* Deprecated Dict
* Unecessary timeout for api

Cleanup for Elixir 1.4

---

lib/exq/manager/server.ex
lib/exq/redis/job_stat.ex
lib/exq/stats/server.ex
test/exq_test.exs
test/job_stat_test.exs

When a node dies, stats are not cleaned up and workers can appear busy. To fix this,
cleanup stats for a host on boot.
Fixes #235 / #227

Cleanup process stats on boot

---

lib/exq/stats/server.ex

For cleanup_processes do not exit if invalid syntax

---

lib/exq.ex
lib/exq/support/config.ex

This is useful when it is better to put it on Phoenix or other supervisor
explicitly. In that case, we can set it to not start automatically via this config.
#255

Allow option to not start Exq on startup

---

lib/exq/worker/server.ex
test/exq_test.exs

Worker GenServer was using `start` instead of `start_link`. It seems that worker was still
was shutting down properly on supervisor shutdown. However, this violates the OTP assumption.
Fixing this, worker shutdown does not honor the shutdown timeout value. This should be fixed as
part of #263, disabled those tests for now.

Fix worker link

---

README.md
lib/exq/support/coercion.ex
lib/exq/support/config.ex
lib/exq/support/opts.ex
test/config_test.exs
test/test_helper.exs

Would love to get Exq supporting the `{:system, "VARNAME"}` format for runtime config...
Thoughts?
-- EDIT --
If you don't like the `{:system, ""}` approach, there are others:
* Exq can specify a fallback environment variable for URL (not from config)
* Exq can provide an [on_init callback similar to Phoenix](https://github.com/phoenixframework/phoenix/blob/7fbf4fc0567a3276c978b434c4f0c658228af276/lib/phoenix/endpoint.ex#L63-L80) to update config when the application starts.
* Exq can [rely less on compile-time config and more on arguments](https://elixirforum.com/t/mix-config-evolutions/4423/19)
If you think you'd merge this, I can add additional tests for when the environment variable is an invalid value (which is why coveralls says the code coverage went down)

Allow {:system, varname} format for configuration

---

README.md
lib/exq.ex
lib/exq/manager/server.ex
lib/exq/support/mode.ex
lib/exq/worker/supervisor.ex
lib/exq/worker_drainer/server.ex
test/exq_test.exs

Gracefully shut down workers

---

lib/exq.ex

I think having Exq.whereis/1 as a separate function is useful. I am using it right now.

add whereis/1 as shortcut for pid of exq instance

---

mix.exs

I bump up uuid version to solve issue #280 . It works fine on Elixir 1.4.5, but not been tested on older version.
Please look on. Thanks.

Update version of uuid dependency

---

.travis.yml
lib/exq/support/opts.ex
test/config_test.exs

This paves the way for SSL support but in the meantime allows one to configure the socket options for the TCP connection
NOTE: the upgrade of redix to v0.6.1 is not important and I can revert it

Pass socket_opts to redix

---

lib/exq/support/mode.ex
test/exq_test.exs
test/mode_test.exs

By default, the supervisor waits only 5 seconds.  It should wait for as long as the :shutdown_timeout option is.
Fixes issue #311

Have top supervisor wait for worker drainer to gracefully terminate

---

lib/exq.ex
lib/exq/manager/server.ex
test/exq_test.exs

It would be great if i can access to the list of all subscriptions via api.
I've added this functionality for my usecase of showing all active queues.
example usage:
{:ok, subscriptions} = Exq.subscriptions(Exq)
{:ok, ["two", "four", "five"]}
short story:
I have 5 queues named one, two, three, four, five
and i want to highlight active queue which is currently subscribed.
if i am subscribing two, four, five
result would be like this: one, `two`, three, `four`, `five`

Add an api to list all subscriptions(active queues)

---

mix.exs

the UUID lib has changed it's name to `elixir_uuid`. The API is exactly the same. Having the old `uuid` and `elixir_uuid` deps is causing dep clash issues in that they both occupy the same namespace. This PR will bring it in line with the newest version and prevent future namespace clashes.
See the note here for more details:
https://github.com/zyro/elixir-uuid#elixir-uuid

Update UUID dep in mix.exs

---

lib/exq/middleware/server.ex

Fix below warning.
```
warning: function init/1 required by behaviour GenServer is not implemented (in module Exq.Middleware.Server).
We will inject a default implementation for now:
def init(args) do
{:ok, args}
end
You can copy the implementation above or define your own that converts the arguments given to GenServer.start_link/3 to the server state.
lib/exq/middleware/server.ex:1
```

Fix init func warning

---

README.md

Just a small thing I noticed in the README. Thanks for exq!!

Fix syntax highlighting in the README

---

mix.exs

There were some breaking changes introduced in redix 0.8.0
Closes #336
Closes #337
(btw, does `mix deps.get` not look at the mix.lock of the dependency to get the sub-dependencies?  I would have expected that but mine got redix 0.8.1 so it failed ¯\_(ツ)_/¯)

Specify less than 0.8.0 on redix version in mix.exs

---

lib/exq/manager/server.ex

When the redis configuration is just the url string and there's a connection error, exq raises an exception instead of displaying the error message.

Don't assume redis_opts is enumerable

---

lib/exq/support/mode.ex
test/exq_test.exs

For our use case, it's less that we want the enqueuer to be independent, but rather we want the processor to be independent, and the other node to be everything else (and I'm assuming this isn't super uncommon, basically being able to add to and delete from the queue from one node, and the other node just processing the queue).  This solution seemed to be the most straight forward way to accomplish that.
Close #341

Allow setting mode to both [:enqueuer, :api]

---

config/config.exs
lib/exq/redis/job_queue.ex
lib/exq/support/coercion.ex
lib/exq/support/opts.ex
test/config_test.exs
test/job_queue_test.exs

First of all, thank you for the great library.
When using it I was surprised that some of the config parameters could use the syntax  `{:system, VAR}` and some others could not.
This MR adds `{:system, VAR}` format support for integer parameters that are not supporting it yet and to boolean parameters.
In addition to integers, I supported `:infinity` for the `:concurrency` parameter. I assumed that no other parameter could be `:infinity` as there are no such tests or documentation.
I can add support for list of string in this or another MR (for `:queues`) if wanted.
A proposition of format could be splitting on comas, i.e. `"a,b,c"` parsed as `["a", "b", "c"]`.
Any suggestion is welcome.

Support load from runtime env for more config params

---

lib/exq/serializers/json_serializer.ex
lib/exq/support/config.ex

Added to ensure that previous versions will still work without needing
to add the json_library property.
Fixes #369

Add default for json_library value

---

mix.exs

Although it's not official full name or SPDX identifier... `Apache 2.0` is more commonly used than `Apache2.0` anyway.

Fix typo in license name

---

lib/exq/redis/connection.ex
test/readonly_reconnect_test.exs
test/test-redis-replica.conf
test/test_helper.exs

This ensures persistent connections are shutdown, forcing a reconnect in scenarios where a Redis node in a HA cluster is switched to READONLY mode.
See https://github.com/akira/exq/issues/381 for details.

Handle AWS Elasticache Redis DNS failover.

---

bench.exs
lib/exq/enqueue_api.ex
lib/exq/enqueuer/server.ex
lib/exq/manager/server.ex
mix.exs
mix.lock

```
Name              ips        average  deviation         median         99th %
enqueue          0.85         1.17 s     ±1.05%         1.17 s         1.20 s
mix run --no-start bench.exs  9.19s user 1.40s system 103% cpu 10.246 total
```
```
Name              ips        average  deviation         median         99th %
enqueue         46.09       21.70 ms    ±27.34%       23.85 ms       29.91 ms
mix run --no-start bench.exs  20.80s user 7.24s system 340% cpu 8.244 total
```
@mrcdll I did an informal benchmark with artificial delay introduced by toxiproxy. This branch performs lot better than the current version. Again, I tried to keep the code change minimal inorder to not break any things. Could you test this branch and see if it solves your issue?
fixes #388

Remove unnecessary serialization of enqueue calls

---

mix.lock
test/test_helper.exs

This will prevent the test from being broken when a new transitive
dependency got added.

start all the apps during test.

---

lib/exq/support/opts.ex
test/config_test.exs

We currently cast the global concurrency config. Make the logic uniform by casting queue level concurrency config as well. fixes #386

cast queue level concurrency

---

CHANGELOG.md
lib/mix/tasks/exq.run.ex

Otherwise we get warnings like below
15:48:47.253 [warn]  Failed to lookup telemetry handlers. Ensure the telemetry application has been started.
15:48:47.357 [warn]  Failed to lookup telemetry handlers. Ensure the telemetry application has been started.

exq.run mix task should start dependent apps as well

---

lib/exq/enqueue_api.ex

The initial comment says the offset is in milliseconds, the doc for the offset says (correctly) it is in seconds. This just corrects the first.

Conflicting units in the doc for enqueue_in

---

config/test.exs
lib/exq/middleware/telemetry.ex
mix.lock
test/config_test.exs
test/middleware_test.exs

This allows you to subscribe to the telemetry events and collect metrics about your jobs. We figured this might be useful to other people in the Exq community.
We used something like the following to collect and display using telemetry metrics:
```
defmodule MyApp.Application do
def start(_type, _args) do
children = [
{:telemetry_poller, measurements: periodic_measurements(), period: 10_000},
{Telemetry.Metrics.ConsoleReporter, metrics: metrics()}
]
opts = [strategy: :one_for_one, name: MyApp.Supervisor]
Supervisor.start_link(children, opts)
end
defp metrics do
[
counter("exq.job.started.count"),
counter("exq.job.started.retry_count"),
counter("exq.job.processed.retry_count"),
distribution("exq.job.processed.duration",
buckets: [0.1, 0.2, 0.3, 0.5, 0.75, 1, 2, 3, 5, 10]
), …
```

middleware to fire telemetry events

---

lib/exq/redis/connection.ex
lib/exq/redis/heartbeat.ex
lib/exq/redis/job_queue.ex
lib/exq/redis/script.ex
test/exq/heartbeat/monitor_test.exs
test/job_queue_test.exs
test/worker_test.exs

Currently, unfinished jobs from backup queue get re-enqueued to the
end of job queue. This commit changes the behaviour and re-enqueue
the jobs to the front of the job queue so they will get picked up soon
after restart.
fixes #300

re-enqueue unfinished jobs to the begining of queue on restart

---

lib/exq/redis/job_queue.ex
lib/exq/redis/script.ex
lib/exq/support/config.ex
test/job_queue_test.exs

The old approach had two issues
* There was no limit on the zrangebyscore call, this could potentially
cause memory issues if there are lot of jobs scheduled within the
current time range.
* The dequeue and enqueue operation is not atomic. The job could be
lost if exq failed to enqueue the job after the zrem command either
due to shutdown or redis connection error
The new approach uses lua script to run the dequeue and enqueue
atomically. A configurable page limit is used to avoid blocking the
redis server for long time.
fixes #318 #315

use lua script to schedule jobs

---

lib/exq/dequeue/behaviour.ex
lib/exq/dequeue/local.ex
lib/exq/manager/server.ex
lib/exq/middleware/manager.ex
lib/exq/support/opts.ex
lib/exq/worker/server.ex
test/config_test.exs
test/middleware_test.exs
test/worker_test.exs

Currently, Exq provides concurrency control per queue per worker node. But if anyone wants to rate limit based on different factors, it's not possible to do unless via middleware. The problem with going via middleware is, the job is already dequeued at that point and the only way to stop further dequeue is via `unsubscribe` API. The unsubscribe API is async, so we can't control the exact number of jobs dequeued via it.
Add the ability to control dequeue operation via a new Behaviour. Exq will provide a default implementation and others can override the default implementation per queue.
I have been working on a POC [exq_limit](https://github.com/ananthakumaran/exq_limit) to validate the API. I will try to test it in the coming weeks.
refer #178

Add ability to control the dequeue

---

lib/exq/manager/server.ex
lib/exq/support/opts.ex
mix.lock
test/config_test.exs

redix added stricter config validation on 0.11.0. It doesn't allow
host/port config if sentinel option is present.
[1] https://github.com/whatyouhide/redix/commit/4ca9146db158d2918e7399e5881ae1aa349fb79f

make it possible to use sentinel with latest redix

---

lib/exq/middleware/logger.ex

Logging everything as info makes it hard to use the log level configuration when we only care about getting logs for errors.
Since these are recoverable errors the warning level makes the most sense to me.

Changing Log level to warn for job errors

---

lib/exq/worker/server.ex

Hello! 👋🏼 
I maintain https://github.com/getsentry/sentry-elixir and have received issues where failed jobs in Exq don't report process metadata from the crashed process (https://github.com/getsentry/sentry-elixir/issues/349). It looks like it's due to using `spawn_link` instead of Elixir modules like Task or GenServer that rely on `:proc_lib` underneath. The change would allow for some more detailed reporting on the state of the worker process is in when it crashed, including parent process, metadata, and more.
I wasn't sure if `Task` was appropriate, but the tests do pass 🙂

use Task instead of spawn_link for starting workers

---

.github/workflows/ci.yml

Hello.
I have some improvement of the CI pipeline you have.
FIrstly, ubuntu-latest version was recently upgraded from 18.04 to 20.04. This causes an error with Elixir installation step:
https://github.com/akira/exq/pull/442/checks?check_run_id=2131663989
So I've changed ubuntu version back to 18.04 until the installer will be updated. 18.04 will be supported until April 2023.
Secondly, there is an annoying fact about Github Actions - sometimes it runs actions twice. For example:
1. You just pushed a commit to a branch - testing workflow will run only once
2. Someone forked your repo and creates a pull request - same thing
3. You've created a new branch (feature, bugfix or release branch), pushed a commit here and also created a pull request to the main branch - two copies of workflow will …

Improve Github Actions

---

lib/exq/manager/server.ex
lib/exq/redis/connection.ex
lib/exq/redis/job_queue.ex
lib/exq/support/redis.ex

Currently, if any of the middleware fails, (notably
Exq.Middleware.Job), it prevents the execution of remaining
middlewares. This is highly problematic as Exq.Middleware.Manager is
essential for Exq to function properly.
In this specific case, if the redis operation in Exq.Middleware.Job
timeouts (or fails), then Exq fails to decrement the busy worker count
and with enough number of such failures, the worker eventually will
stop picking up new jobs.
This commit tries to improve the conditions by adding a retry for
`remove_job_from_backup` operation. Retrying is ok in this case as the
operation is idempotent

handle timeouts on middleware pipeline

---

lib/exq/manager/server.ex
lib/exq/support/mode.ex
lib/exq/worker/supervisor.ex
test/mode_test.exs

* Update from deprecated `Supervisor.start_child/2` with a list of args and `Supervisor.Spec.supervise/2` to `DynamicSupervisor`
* Update from deprecated `Supervisor.Spec.worker/3` to `Supervisor.child_spec/2`
```
warning: Supervisor.Spec.supervisor/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
lib/exq/support/mode.ex:34: Exq.Support.Mode.children/2
warning: Supervisor.Spec.worker/2 is deprecated. Use the new child specifications outlined in the Supervisor module instead
Found at 13 locations:
lib/exq/support/mode.ex:22: Exq.Support.Mode.children/1
lib/exq/support/mode.ex:31: Exq.Support.Mode.children/2
lib/exq/support/mode.ex:32: Exq.Support.Mode.children/2
lib/exq/support/mode.ex:33: Exq.Support.Mode.children/2
lib/exq/support/mode.ex:35: …
```

Replace deprecated Supervisor calls

---

README.md
lib/exq.ex

This is related to https://github.com/akira/exq/issues/387 and is a logical continuation of https://github.com/akira/exq/pull/453/files
The current PR adds `def child_spec` to `Exq` and removes `supervisor` calls from `application.ex` to match the latest version of Phoenix.
Tested with Elixir 1.7 and Elixir 1.11 (couldn't start on Elixir 1.6 because of `:telemetry` dependency)

Update README: use latest Phoenix child spec style

---

lib/exq/api.ex
lib/exq/api/server.ex
lib/exq/manager/server.ex
lib/exq/middleware/stats.ex
lib/exq/node/server.ex
lib/exq/redis/job_stat.ex
lib/exq/serializers/json_serializer.ex
lib/exq/stats/server.ex
lib/exq/support/mode.ex
lib/exq/support/node.ex
lib/exq/support/opts.ex
lib/exq/support/process.ex
lib/exq/worker/supervisor.ex
test/api_test.exs
test/config_test.exs
test/exq_test.exs
test/job_stat_test.exs
test/worker_test.exs

Adds support for sidekiq 5 UI. Threads (aka concurrency) is set to 0 since we allow custom dequeuers which might allow jobs based on different constrain. Busy count should be accurate. The `Quiet` button would cause the node to unsubscribe from all queues.
1. This change introduces the concept of worker nodes. The list of active worker nodes is tracked in a set `exq:processes`. For each worker node, some metadata like subscribed queues, number of busy jobs, start time etc are tracked. A new GenServer called `Exq.Node.Server` is introduced to send heartbeat and the metadata info to the redis every 5 seconds. It also cleans up the dead worker nodes' info from redis.
2. The concept of per worker signal is introduced. Currently we support `TSTP` (quiet), which will ask the worker node to …

Sidekiq 5 UI compatibility

---

lib/exq/worker/server.ex

Fixes compile time @doc redefined warnings. Ref. https://github.com/elixir-lang/elixir/issues/7817
```
Compiling 53 files (.ex)
warning: redefining @doc attribute previously set at line 19.
Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:
@doc """
new docs
"""
def handle_cast(...)
lib/exq/worker/server.ex:107: Exq.Worker.Server.handle_cast/2
warning: redefining @doc attribute previously set at line 19.
Please remove the duplicate docs. If instead you want to override a previously defined @doc, attach the @doc attribute to a function head (the function signature not followed by any do-block). For example:
@doc """
new docs
"""
def …
```

maint: fix @doc refined warnings.

---

lib/exq/api.ex
lib/exq/api/server.ex
lib/exq/redis/job_stat.ex
test/api_test.exs

This api will be used by exq_ui to implement unsubscibe all/quiet
feature in the Busy page

Add api to send signal to worker nodes

---

README.md
lib/exq/adapters/queue.ex
lib/exq/adapters/queue/mock.ex
lib/exq/adapters/queue/redis.ex
lib/exq/enqueue_api.ex
lib/exq/mock.ex
lib/exq/redis/connection.ex
lib/exq/redis/job_queue.ex
lib/exq/redis/script.ex
test/exq_test.exs
test/fake_mode_test.exs
test/inline_mode_test.exs

This PR addresses: 
https://github.com/akira/exq/issues/482
API:
```elixir
jobs = [
[queue_1, time_1, worker_1, args_1, options_1],
[queue_2, time_2, worker_2, args_2, options_2],
[queue_3, time_3, worker_3, args_3, options_3]
...
]
Exq.Enqueuer.enqueue_all(Exq.Enqueuer, jobs)
{:error, reason}
[
{:ok, jid_1},
{:ok, jid_2},
{:ok, jid_3}
]
[
{:ok, jid_1},
{:conflict, jid_2},
{:conflict, jid_3}
]
```
@ananthakumaran Here is a quick draft, please take a quick look and let me know if I am missing anything obvious, I will get back to polishing, adding tests etc once I get an inital thumbs up.
cheers!

Add enqueue_all for enqueuing a batch of jobs atomically

---

.github/workflows/ci.yml
mix.exs
mix.lock

Allow Poison 5.0.0 to be used.

Bump version of Poison

---

CHANGELOG.md

This is my first open source contribution. Please review and merge

Fixed the typo in queue spelling in Changelog.md file

---

lib/exq/api.ex
lib/exq/api/server.ex
lib/exq/redis/job_queue.ex
test/api_test.exs

According to [this issue](https://github.com/akira/exq/issues/494) Addition of `unlock` option to `remove_*_jobs` functions family

Add option to remove unique token

---

.github/workflows/ci.yml
README.md
config/test.exs
lib/exq/middleware/pipeline.ex
lib/exq/middleware/snooze.ex
lib/exq/redis/job_queue.ex
test/config_test.exs
test/exq_test.exs
test/job_queue_test.exs
test/middleware_test.exs

Implementation is same as how retry is implemented, just that retry_count is not incremented, so a job can be snoozed unlimited times

Add ability to snooze job

---

lib/exq/support/mode.ex

Enqueuer should be started before worker and shutdown after worker, as worker drainer might keep the worker process alive for `shutdown_timeout` and during that period, any enqueue operation inside the worker process will fail

Fix shutdown order of worker and enqueuer
