akira/exq

lib/exq/stats.ex

Changing failure to be a redis list. See issue #58

---

README.md
mix.exs

Loosen plug dependency, closes #78

Loosen plug

---

mix.exs
mix.lock
test/performance_test.exs

Upgrade timex

---

lib/exq.ex
lib/exq/manager/server.ex
test/exq_test.exs

Re-branched dynamic subscription implementation to clean up branch history. Implements dynamic subscribe and unsubscribe actions as well as tests for each.

Cleaned dynamic subscription

---

lib/exq/manager/server.ex
lib/exq/scheduler/scheduler.ex

I assume this `UKNOWN` is supposed to be `UNKNOWN`?

Fix typo in log

---

lib/exq/manager/server.ex
lib/exq/redis/job_queue.ex

* Fix issue not matching connection error on dequeue
* Add rescue timeout helper

Failure conditions for Redis down or timeout

---

lib/exq/manager/server.ex
lib/exq/redis/connection.ex
lib/exq/redis/job_queue.ex
lib/exq/scheduler/server.ex
test/exq_test.exs
test/job_queue_test.exs

* kick off timer start on scheduler init versus manager
* Cleanup scheduler dequeue to remove unneeded code

Scheduler fixes

---

lib/exq/redis/job_queue.ex
mix.exs

support Elixir 1.2.0

---

lib/exq/middleware/logger.ex

Actually, it borrows the code from plug.

log time in ms, µs just as phoenix/plug does

---

README.md

README update for use with Phoenix

---

README.md
lib/exq/middleware/server.ex
lib/exq/redis/job_queue.ex
lib/exq/support/job.ex
test/test_helper.exs

I hope I did this right. This is my first PR.
I just found some spelling errors and fixed them.

Spelling corrections

---

README.md
lib/exq/support/config.ex
lib/exq/support/opts.ex
lib/exq/worker/supervisor.ex
test/config_test.exs
test/exq_test.exs

This is an implementation for #187. Please let me know if there's anything you'd like me to tweak. Thanks!

Add shutdown_timeout option

---

lib/exq/support/config.ex

Default config option for reconnect_on_sleep

---

lib/exq/redis/job_queue.ex

sidekiq also allows a integer value instead of boolean for the retry key(https://github.com/mperham/sidekiq/wiki/Advanced-Options#workers). Incase of integer, it specifies the max retry count for the specific worker.

add support for worker specific retry count

---

lib/exq/support/randomize.ex

Use Enum.random

---

lib/exq.ex
lib/exq/manager/server.ex
lib/exq/support/mode.ex
lib/exq/support/opts.ex
lib/exq/worker/metadata.ex
lib/exq/worker/server.ex
test/config_test.exs
test/metadata_test.exs
test/middleware_test.exs
test/test_helper.exs
test/worker_test.exs

expose job metadata to worker process

---

lib/exq/worker/server.ex

While using Exq, `mix deps.compile` gave three warnings on unsafe variable usage.
This PR addresses these warnings.
Below is the warning Mix would output:
```
warning: the variable "state" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:
case int do
1 -> atom = :one
2 -> atom = :two
end
should be written as
atom =
case int do
1 -> :one
2 -> :two
end
```

address some variable unsafe mix compile warnings

---

README.md

Following https://github.com/akira/exq/issues/259

Document caveats with dynamic nodes

---

lib/exq/manager/server.ex

Remove password from error logging

---

lib/exq/redis/connection.ex
lib/exq/support/mode.ex
lib/exq/support/opts.ex
mix.exs
mix.lock
test/config_test.exs
test/exq_test.exs
test/test-sentinel.conf
test/test_helper.exs

make redis module name and start_link args configurable

---

config/test.exs
lib/exq/redis/job_queue.ex
test/job_queue_test.exs

Default option in sidekiq sets retry => true [1]. Adding a matcher in exq to retry such jobs.
[1] https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L41

Ensure sidekiq jobs are retried.

---

README.md

To include current Timex methods

Update `enqueue_at` example in README

---

lib/exq/support/time.ex

Fix deprecated time unit

---

lib/exq/middleware/logger.ex

Formatting for worker log, remove time unit

---

lib/exq/redis/job_stat.ex

As explained [here](https://github.com/akira/exq/issues/383), I've implemented a cursored call using `SCAN` instead of `KEYS`, to avoid freezing redis production instances that could possibly store million of keys related to exq jobs.
I still have to find a way to easily test this, since I seem to have problems running the tests using a dockerized version of redis, along with the default `test.exs` (even though I've set the `REDIS_PORT` variable appropriately)

Replace KEYS with a cursored call to SCAN for realtime stats

---

README.md

Fix a typo in the description

---

mix.exs
mix.lock

relax poison dependency version

---

lib/exq/api.ex

This adds in documentation for additional functions in the Api module.

Api Module Documentation

---

.github/workflows/ci.yml
README.md
config/config.exs
config/test.exs
lib/exq/enqueue_api.ex
lib/exq/middleware/pipeline.ex
lib/exq/middleware/unique.ex
lib/exq/redis/connection.ex
lib/exq/redis/job_queue.ex
lib/exq/redis/script.ex
lib/exq/serializers/json_serializer.ex
lib/exq/support/config.ex
lib/exq/support/job.ex
test/config_test.exs
test/exq_test.exs
test/job_queue_test.exs
test/middleware_test.exs
test/test_helper.exs
test/worker_test.exs

Check the readme file for api usage details. The API semantics are based [sidekiq unique jobs](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs)
fixes #184 #380

Add unique job feature

---

.github/workflows/ci.yml

Remove extra redirection. See https://github.com/erlef/setup-beam/issues/20

Use erlef/setup-beam and bump versions
